# Generated by Django 5.0.6 on 2024-06-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('image', models.ImageField(upload_to='category/', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ('-added_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ('-added_at',),
            },
        ),
    ]
